apiVersion: v1
kind: Service
metadata:
  name: {{ include "greeter.fullname" . }}
  labels:
    {{- include "greeter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "greeter.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
